dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-test
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: jx-go-grpc-rest
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.9
- name: jx-node-lb
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
